services:
  web:
    build: .
    env_file:
      # we'll respect prisma's DATABASE_URL so must execute `prisma db push`
      # before composing
      - prisma/.env
    environment:
      REDIS_URL: redis://redis
      # fill this out. https://developer.spotify.com/dashboard
      SPOTIFY_CLIENT_ID:
      SPOTIFY_CLIENT_SECRET:
      SPOTIFY_REDIRECT_URI: http://localhost:3001/spotify/callback
    ports:
      - 3001:3001
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    restart: always
